package simplelibrary.poo;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import simplelibrary.poo.dao.LivroDAO;
import simplelibrary.poo.dao.UsuarioDAO;
import simplelibrary.poo.model.Livro;
import simplelibrary.poo.model.Usuario;

/**
 *
 * @author Fábio Henrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Users = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nome_User = new javax.swing.JTextField();
        Email_User = new javax.swing.JTextField();
        Buttun_Cadastro = new javax.swing.JButton();
        Listar_Users_cadastrados = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista_Users = new javax.swing.JTable();
        Books = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Titulo_txt = new javax.swing.JTextField();
        Gên_txt = new javax.swing.JTextField();
        Year_txt = new javax.swing.JTextField();
        ID_Autor_txt = new javax.swing.JTextField();
        Button_Cadastro_Books = new javax.swing.JButton();
        listar_livros_cadastrados = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_books = new javax.swing.JTable();
        Emprestimo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ID_book_txt = new javax.swing.JTextField();
        ID_User_txt = new javax.swing.JTextField();
        Emprestar_button = new javax.swing.JButton();
        Devolver_button = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome :");

        jLabel2.setText("Email :");

        Nome_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nome_UserActionPerformed(evt);
            }
        });

        Email_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_UserActionPerformed(evt);
            }
        });

        Buttun_Cadastro.setText("Cadastrar usuário");
        Buttun_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttun_CadastroActionPerformed(evt);
            }
        });

        Listar_Users_cadastrados.setText("Listar Usuários");
        Listar_Users_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_Users_cadastradosActionPerformed(evt);
            }
        });

        Lista_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Status"
            }
        ));
        jScrollPane3.setViewportView(Lista_Users);

        javax.swing.GroupLayout UsersLayout = new javax.swing.GroupLayout(Users);
        Users.setLayout(UsersLayout);
        UsersLayout.setHorizontalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nome_User, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Email_User, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Listar_Users_cadastrados)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersLayout.createSequentialGroup()
                        .addComponent(Buttun_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        UsersLayout.setVerticalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nome_User))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_User))
                        .addGap(86, 86, 86)
                        .addComponent(Buttun_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(Listar_Users_cadastrados))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", Users);

        jLabel3.setText("Título :");

        jLabel4.setText("Ano :");

        jLabel5.setText("Gênero :");

        jLabel6.setText("ID Autor :");

        Titulo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titulo_txtActionPerformed(evt);
            }
        });

        Gên_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gên_txtActionPerformed(evt);
            }
        });

        Year_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_txtActionPerformed(evt);
            }
        });

        ID_Autor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_Autor_txtActionPerformed(evt);
            }
        });

        Button_Cadastro_Books.setText("Cadastrar ");
        Button_Cadastro_Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Cadastro_BooksActionPerformed(evt);
            }
        });

        listar_livros_cadastrados.setText("Listar livros");
        listar_livros_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_livros_cadastradosActionPerformed(evt);
            }
        });

        Lista_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Gênero", "Ano", "ID Autor", "Status"
            }
        ));
        jScrollPane2.setViewportView(Lista_books);

        javax.swing.GroupLayout BooksLayout = new javax.swing.GroupLayout(Books);
        Books.setLayout(BooksLayout);
        BooksLayout.setHorizontalGroup(
            BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooksLayout.createSequentialGroup()
                .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Cadastro_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BooksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(BooksLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Year_txt))
                                .addGroup(BooksLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ID_Autor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(BooksLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Titulo_txt))
                                .addGroup(BooksLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Gên_txt)))
                            .addComponent(listar_livros_cadastrados))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        BooksLayout.setVerticalGroup(
            BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooksLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BooksLayout.createSequentialGroup()
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gên_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_Autor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(Button_Cadastro_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listar_livros_cadastrados)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Livros", Books);

        jLabel7.setText("ID Usuário :");

        jLabel8.setText("ID Livro :");

        Emprestar_button.setText("Emprestar");
        Emprestar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emprestar_buttonActionPerformed(evt);
            }
        });

        Devolver_button.setText("Devolver");
        Devolver_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Devolver_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmprestimoLayout = new javax.swing.GroupLayout(Emprestimo);
        Emprestimo.setLayout(EmprestimoLayout);
        EmprestimoLayout.setHorizontalGroup(
            EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmprestimoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_User_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_book_txt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EmprestimoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Emprestar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(Devolver_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        EmprestimoLayout.setVerticalGroup(
            EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmprestimoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_User_txt))
                .addGap(18, 18, 18)
                .addGroup(EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_book_txt))
                .addGap(47, 47, 47)
                .addGroup(EmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Devolver_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emprestar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emprestimo", Emprestimo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_UserActionPerformed

    private void Buttun_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttun_CadastroActionPerformed
     
        String nome = Nome_User.getText();
        String email = Email_User.getText();

        // ✅ Validação primeiro
        if (nome.isBlank() || email.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha nome e email!");
            return;
        }

        try {
            simplelibrary.poo.model.Usuario usuario =
                    new simplelibrary.poo.model.Usuario(nome, email, "ATIVO");

            simplelibrary.poo.dao.UsuarioDAO dao =
                    new simplelibrary.poo.dao.UsuarioDAO();

            dao.cadastrar(usuario);

            javax.swing.JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");

            Nome_User.setText("");
            Email_User.setText("");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário!");
            e.printStackTrace();
        }

    }//GEN-LAST:event_Buttun_CadastroActionPerformed

    private void Nome_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nome_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nome_UserActionPerformed

    private void Titulo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titulo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titulo_txtActionPerformed

    private void Gên_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gên_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gên_txtActionPerformed

    private void Year_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_txtActionPerformed

    private void ID_Autor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_Autor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_Autor_txtActionPerformed

    private void Button_Cadastro_BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Cadastro_BooksActionPerformed
        try {

            String titulo = Titulo_txt.getText();
            String genero = Gên_txt.getText();
            int ano = Integer.parseInt(Year_txt.getText());
            int idAutor = Integer.parseInt(ID_Autor_txt.getText());

            if (titulo.isBlank() || genero.isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
                return;
            }

            simplelibrary.poo.model.Livro livro =
                    new simplelibrary.poo.model.Livro(titulo, ano, genero, idAutor, "DISPONIVEL");

            simplelibrary.poo.dao.LivroDAO dao =
                    new simplelibrary.poo.dao.LivroDAO();

            dao.cadastrar(livro);

            javax.swing.JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");

            Titulo_txt.setText("");
            Gên_txt.setText("");
            Year_txt.setText("");
            ID_Autor_txt.setText("");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar livro!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Button_Cadastro_BooksActionPerformed

    private void Emprestar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emprestar_buttonActionPerformed
        try {

            int idUsuario = Integer.parseInt(ID_User_txt.getText());
            int idLivro = Integer.parseInt(ID_book_txt.getText());

            simplelibrary.poo.dao.EmprestimoDAO dao =
                    new simplelibrary.poo.dao.EmprestimoDAO();

            dao.emprestar(idUsuario, idLivro);

            javax.swing.JOptionPane.showMessageDialog(this, "Empréstimo realizado com sucesso!");

            ID_User_txt.setText("");
            ID_book_txt.setText("");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao emprestar livro!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Emprestar_buttonActionPerformed

    private void Devolver_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Devolver_buttonActionPerformed
        try {

            int idLivro = Integer.parseInt(ID_book_txt.getText());

            simplelibrary.poo.dao.EmprestimoDAO dao =
                    new simplelibrary.poo.dao.EmprestimoDAO();

            // Aqui você precisa do id do empréstimo real
            int idEmprestimo = 1; // temporário para teste

            dao.devolver(idEmprestimo, idLivro);

            javax.swing.JOptionPane.showMessageDialog(this, "Livro devolvido com sucesso!");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao devolver livro!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Devolver_buttonActionPerformed

    private void Listar_Users_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_Users_cadastradosActionPerformed
        try {
            UsuarioDAO dao = new UsuarioDAO();
            List<Usuario> usuarios = dao.listar();

            DefaultTableModel model = (DefaultTableModel) Lista_Users.getModel();
            model.setRowCount(0);

            for (Usuario u : usuarios) {
                model.addRow(new Object[]{
                    u.getId(),        // ✅ CORRIGIDO AQUI
                    u.getNome(),
                    u.getEmail(),
                    u.getStatus()
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao listar usuários!");
        }
    }//GEN-LAST:event_Listar_Users_cadastradosActionPerformed

    private void listar_livros_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_livros_cadastradosActionPerformed
             try {
                simplelibrary.poo.dao.LivroDAO dao = new simplelibrary.poo.dao.LivroDAO();
                java.util.List<simplelibrary.poo.model.Livro> livros = dao.listar();

                javax.swing.table.DefaultTableModel model =
                        (javax.swing.table.DefaultTableModel) Lista_books.getModel();

                model.setRowCount(0); // limpa a tabela

                for (simplelibrary.poo.model.Livro l : livros) {
                    model.addRow(new Object[]{
                        l.getId(),               // ✅ era getIdLivro()
                        l.getTitulo(),
                        l.getGenero(),
                        l.getAnoPublicacao(),    // ✅ era getAnoPublicicacao()
                        l.getIdAutor(),
                        l.getStatus()
                    });
                }

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao listar livros!");
            }
    }//GEN-LAST:event_listar_livros_cadastradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Books;
    private javax.swing.JButton Button_Cadastro_Books;
    private javax.swing.JButton Buttun_Cadastro;
    private javax.swing.JButton Devolver_button;
    private javax.swing.JTextField Email_User;
    private javax.swing.JButton Emprestar_button;
    private javax.swing.JPanel Emprestimo;
    private javax.swing.JTextField Gên_txt;
    private javax.swing.JTextField ID_Autor_txt;
    private javax.swing.JTextField ID_User_txt;
    private javax.swing.JTextField ID_book_txt;
    private javax.swing.JTable Lista_Users;
    private javax.swing.JTable Lista_books;
    private javax.swing.JButton Listar_Users_cadastrados;
    private javax.swing.JTextField Nome_User;
    private javax.swing.JTextField Titulo_txt;
    private javax.swing.JPanel Users;
    private javax.swing.JTextField Year_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listar_livros_cadastrados;
    // End of variables declaration//GEN-END:variables
}
